
package view;
import java.awt.Color;

import javax.swing.JFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import dal.ModulodeConexão;
import net.proteanit.sql.DbUtils;
import static view.RealizarServiços.*;
import static view.Quartos.*;
import static view.AlugarSalão.*;
import view2.*;
/**
 *
 * @author Ramiro Dantas
 */
public class DashboardADM extends javax.swing.JFrame {
        Connection conexao = null;
        PreparedStatement pst = null;
    ResultSet rs = null;
        private void read(){
        String sql = "Select * from pedidoservico";        
        try { 
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
           
                tblServico.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
        } catch (Exception e) {
            new Erro().setVisible(true);
        }
            
    }
       
       private void add(){
           String sql = "Select * from quartos";        
        try { 
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
                tblQuartos.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
        } catch (Exception e) {
            new Erro().setVisible(true);
        }
       }
    private void inserir() {
        String sql = "Select * from alugarsalao";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            tblSalao.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
        } catch (Exception e) {
            new Erro().setVisible(true);
        }
    }
    /**:
     * Creates new form DashboardADM
     */
    public DashboardADM() {
        initComponents();
        conexao = ModulodeConexão.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fechar1 = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Painelprincipal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Recepcionista = new javax.swing.JButton();
        Hóspede = new javax.swing.JButton();
        Reserva = new javax.swing.JButton();
        Servico = new javax.swing.JButton();
        Salao = new javax.swing.JButton();
        Relatorios = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        Quartos = new javax.swing.JButton();
        Gerente = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        CadastrarAdm = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrador");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 0, 72));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fechar1.setFont(new java.awt.Font("SF Sports Night NS Upright", 1, 36)); // NOI18N
        fechar1.setForeground(new java.awt.Color(255, 255, 255));
        fechar1.setText("X");
        fechar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fechar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fechar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fechar1MouseExited(evt);
            }
        });
        jPanel1.add(fechar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        minimizar.setFont(new java.awt.Font("Rubik", 1, 36)); // NOI18N
        minimizar.setForeground(new java.awt.Color(255, 255, 255));
        minimizar.setText("_");
        minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizarMouseExited(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("User");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 730, 60));

        jPanel2.setBackground(new java.awt.Color(41, 58, 128));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Admin.png"))); // NOI18N

        Painelprincipal.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Painelprincipal.setForeground(new java.awt.Color(255, 255, 255));
        Painelprincipal.setText("Administrador");
        Painelprincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Painelprincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PainelprincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PainelprincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PainelprincipalMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(243, 148, 34));
        jLabel3.setText("_____________");

        Recepcionista.setBackground(new java.awt.Color(1, 0, 72));
        Recepcionista.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Recepcionista.setForeground(new java.awt.Color(255, 255, 255));
        Recepcionista.setText("Recepcionista");
        Recepcionista.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Recepcionista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Recepcionista.setFocusPainted(false);
        Recepcionista.setPreferredSize(new java.awt.Dimension(89, 28));
        Recepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RecepcionistaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RecepcionistaMouseExited(evt);
            }
        });
        Recepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecepcionistaActionPerformed(evt);
            }
        });

        Hóspede.setBackground(new java.awt.Color(1, 0, 72));
        Hóspede.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Hóspede.setForeground(new java.awt.Color(255, 255, 255));
        Hóspede.setText("Hóspede");
        Hóspede.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Hóspede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hóspede.setFocusPainted(false);
        Hóspede.setPreferredSize(new java.awt.Dimension(89, 28));
        Hóspede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HóspedeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HóspedeMouseExited(evt);
            }
        });
        Hóspede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HóspedeActionPerformed(evt);
            }
        });

        Reserva.setBackground(new java.awt.Color(1, 0, 72));
        Reserva.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Reserva.setForeground(new java.awt.Color(255, 255, 255));
        Reserva.setText("Reserva");
        Reserva.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Reserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reserva.setFocusPainted(false);
        Reserva.setPreferredSize(new java.awt.Dimension(89, 28));
        Reserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReservaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReservaMouseExited(evt);
            }
        });
        Reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservaActionPerformed(evt);
            }
        });

        Servico.setBackground(new java.awt.Color(1, 0, 72));
        Servico.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Servico.setForeground(new java.awt.Color(255, 255, 255));
        Servico.setText("Serviços");
        Servico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Servico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Servico.setFocusPainted(false);
        Servico.setPreferredSize(new java.awt.Dimension(89, 28));
        Servico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ServicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ServicoMouseExited(evt);
            }
        });
        Servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServicoActionPerformed(evt);
            }
        });

        Salao.setBackground(new java.awt.Color(1, 0, 72));
        Salao.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Salao.setForeground(new java.awt.Color(255, 255, 255));
        Salao.setText("Salão");
        Salao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Salao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salao.setFocusPainted(false);
        Salao.setPreferredSize(new java.awt.Dimension(89, 28));
        Salao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalaoMouseExited(evt);
            }
        });
        Salao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaoActionPerformed(evt);
            }
        });

        Relatorios.setBackground(new java.awt.Color(1, 0, 72));
        Relatorios.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Relatorios.setForeground(new java.awt.Color(255, 255, 255));
        Relatorios.setText("Relatórios");
        Relatorios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Relatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Relatorios.setFocusPainted(false);
        Relatorios.setPreferredSize(new java.awt.Dimension(89, 28));
        Relatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RelatoriosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RelatoriosMouseExited(evt);
            }
        });
        Relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatoriosActionPerformed(evt);
            }
        });

        Sair.setBackground(new java.awt.Color(1, 0, 72));
        Sair.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Sair.setForeground(new java.awt.Color(255, 255, 255));
        Sair.setText("Sair");
        Sair.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sair.setFocusPainted(false);
        Sair.setPreferredSize(new java.awt.Dimension(89, 28));
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SairMouseExited(evt);
            }
        });
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        Quartos.setBackground(new java.awt.Color(1, 0, 72));
        Quartos.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Quartos.setForeground(new java.awt.Color(255, 255, 255));
        Quartos.setText("Quartos");
        Quartos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Quartos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Quartos.setFocusPainted(false);
        Quartos.setPreferredSize(new java.awt.Dimension(89, 28));
        Quartos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QuartosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QuartosMouseExited(evt);
            }
        });
        Quartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuartosActionPerformed(evt);
            }
        });

        Gerente.setBackground(new java.awt.Color(1, 0, 72));
        Gerente.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Gerente.setForeground(new java.awt.Color(255, 255, 255));
        Gerente.setText("Gerente");
        Gerente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Gerente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Gerente.setFocusPainted(false);
        Gerente.setPreferredSize(new java.awt.Dimension(89, 28));
        Gerente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GerenteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GerenteMouseExited(evt);
            }
        });
        Gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Painelprincipal))
            .addComponent(jLabel3)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Gerente, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Hóspede, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Reserva, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Servico, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Salao, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Quartos, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Painelprincipal)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)))
                .addGap(13, 13, 13)
                .addComponent(Gerente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Hóspede, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Reserva, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Servico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Salao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Quartos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, 720));

        jDesktopPane1.setBackground(new java.awt.Color(1, 0, 56));

        CadastrarAdm.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        CadastrarAdm.setForeground(new java.awt.Color(255, 255, 255));
        CadastrarAdm.setText("*Cadastrar Administrador");
        CadastrarAdm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CadastrarAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarAdmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CadastrarAdmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CadastrarAdmMouseExited(evt);
            }
        });
        jDesktopPane1.add(CadastrarAdm);
        CadastrarAdm.setBounds(50, 320, 270, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dash.png"))); // NOI18N
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(0, 0, 730, 630);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 730, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fechar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechar1MouseClicked

        System.exit(0);
    }//GEN-LAST:event_fechar1MouseClicked

    private void fechar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechar1MouseEntered
        fechar1.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_fechar1MouseEntered

    private void fechar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechar1MouseExited
        fechar1.setForeground(Color.WHITE);
    }//GEN-LAST:event_fechar1MouseExited

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked

        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void minimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseEntered

        minimizar.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_minimizarMouseEntered

    private void minimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseExited

        minimizar.setForeground(Color.WHITE);
    }//GEN-LAST:event_minimizarMouseExited

    private void RecepcionistaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecepcionistaMouseEntered
       Recepcionista.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_RecepcionistaMouseEntered

    private void RecepcionistaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecepcionistaMouseExited
       Recepcionista.setForeground(Color.WHITE);
    }//GEN-LAST:event_RecepcionistaMouseExited

    private void HóspedeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HóspedeMouseEntered
       Hóspede.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_HóspedeMouseEntered

    private void HóspedeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HóspedeMouseExited
        Hóspede.setForeground(Color.WHITE);
    }//GEN-LAST:event_HóspedeMouseExited

    private void RecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecepcionistaActionPerformed
        CadastrarRecepcionista Cr = new CadastrarRecepcionista();
        jDesktopPane1.add(Cr);
        Cr.setVisible(true);
        ((BasicInternalFrameUI)Cr.getUI()).setNorthPane(null);
    }//GEN-LAST:event_RecepcionistaActionPerformed

    private void PainelprincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PainelprincipalMouseClicked
        PainelPrincipalADM Pp = new PainelPrincipalADM();
       jDesktopPane1.add(Pp);
       Pp.setVisible(true);
       ((BasicInternalFrameUI)Pp.getUI()).setNorthPane(null);   
    }//GEN-LAST:event_PainelprincipalMouseClicked

    private void PainelprincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PainelprincipalMouseEntered
        Painelprincipal.setForeground(Color.LIGHT_GRAY);
        
    }//GEN-LAST:event_PainelprincipalMouseEntered

    private void PainelprincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PainelprincipalMouseExited
        Painelprincipal.setForeground(Color.WHITE);
    }//GEN-LAST:event_PainelprincipalMouseExited
        // TODO add your handling code here:

    private void SalaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaoActionPerformed
      AlugarSalão As = new AlugarSalão();
       jDesktopPane1.add(As);
       As.setVisible(true);
       ((BasicInternalFrameUI)As.getUI()).setNorthPane(null);
       inserir();
    }//GEN-LAST:event_SalaoActionPerformed

    private void ReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservaActionPerformed
       RealizarReserva Rr = new RealizarReserva();
       jDesktopPane1.add(Rr);
       Rr.setVisible(true);
       ((BasicInternalFrameUI)Rr.getUI()).setNorthPane(null);
    }//GEN-LAST:event_ReservaActionPerformed

    private void ReservaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservaMouseEntered
        Reserva.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_ReservaMouseEntered

    private void ReservaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservaMouseExited
        Reserva.setForeground(Color.WHITE);
    }//GEN-LAST:event_ReservaMouseExited

    private void HóspedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HóspedeActionPerformed
        CadastrarHóspede Ch = new CadastrarHóspede();
        jDesktopPane1.add(Ch);
        Ch.setVisible(true);
        ((BasicInternalFrameUI)Ch.getUI()).setNorthPane(null);
    }//GEN-LAST:event_HóspedeActionPerformed

    private void ServicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServicoMouseEntered
        Servico.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_ServicoMouseEntered

    private void ServicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServicoMouseExited
        Servico.setForeground(Color.WHITE);
    }//GEN-LAST:event_ServicoMouseExited

    private void SalaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalaoMouseEntered
        Salao.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_SalaoMouseEntered

    private void SalaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalaoMouseExited
       Salao.setForeground(Color.WHITE);
    }//GEN-LAST:event_SalaoMouseExited

    private void RelatoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelatoriosMouseEntered
        Relatorios.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_RelatoriosMouseEntered

    private void RelatoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelatoriosMouseExited
        Relatorios.setForeground(Color.WHITE);
    }//GEN-LAST:event_RelatoriosMouseExited

    private void QuartosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuartosMouseEntered
      Quartos.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_QuartosMouseEntered

    private void QuartosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuartosMouseExited
        Quartos.setForeground(Color.WHITE);
    }//GEN-LAST:event_QuartosMouseExited

    private void SairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseEntered
      Sair.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_SairMouseEntered

    private void SairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseExited
        Sair.setForeground(Color.WHITE);
    }//GEN-LAST:event_SairMouseExited

    private void RelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatoriosActionPerformed
       GerarRelatórios Gr = new GerarRelatórios();
       jDesktopPane1.add(Gr);
       Gr.setVisible(true);
       ((BasicInternalFrameUI)Gr.getUI()).setNorthPane(null);
    }//GEN-LAST:event_RelatoriosActionPerformed

    private void GerenteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GerenteMouseEntered
        Gerente.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_GerenteMouseEntered

    private void GerenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GerenteMouseExited
        Gerente.setForeground(Color.white);
    }//GEN-LAST:event_GerenteMouseExited

    private void GerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenteActionPerformed
          CadastrarGerente Cg = new CadastrarGerente();
       jDesktopPane1.add(Cg);
       Cg.setVisible(true);
       ((BasicInternalFrameUI)Cg.getUI()).setNorthPane(null);
    }//GEN-LAST:event_GerenteActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
       DashboardADM.this.dispose();
       new Teladelogin().setVisible(true);
    }//GEN-LAST:event_SairActionPerformed

    private void ServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServicoActionPerformed
        RealizarServiços Rs = new RealizarServiços();
        jDesktopPane1.add(Rs);
        Rs.setVisible(true);
        ((BasicInternalFrameUI)Rs.getUI()).setNorthPane(null);
        read();
    }//GEN-LAST:event_ServicoActionPerformed

    private void QuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuartosActionPerformed
       Quartos Q = new Quartos();
       jDesktopPane1.add(Q);
       Q.setVisible(true);
       ((BasicInternalFrameUI)Q.getUI()).setNorthPane(null);
       add();
    }//GEN-LAST:event_QuartosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void CadastrarAdmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarAdmMouseClicked
       new CadastrarADM().setVisible(true);
    }//GEN-LAST:event_CadastrarAdmMouseClicked

    private void CadastrarAdmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarAdmMouseEntered
      CadastrarAdm.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_CadastrarAdmMouseEntered

    private void CadastrarAdmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarAdmMouseExited
       CadastrarAdm.setForeground(Color.WHITE);
    }//GEN-LAST:event_CadastrarAdmMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadastrarAdm;
    private javax.swing.JButton Gerente;
    private javax.swing.JButton Hóspede;
    private javax.swing.JLabel Painelprincipal;
    private javax.swing.JButton Quartos;
    private javax.swing.JButton Recepcionista;
    private javax.swing.JButton Relatorios;
    private javax.swing.JButton Reserva;
    private javax.swing.JButton Sair;
    private javax.swing.JButton Salao;
    private javax.swing.JButton Servico;
    private javax.swing.JLabel fechar1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel minimizar;
    // End of variables declaration//GEN-END:variables

    }

