
package view;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import dal.ModulodeConexão;
import net.proteanit.sql.DbUtils;
import static view.AlugarSalão.tblSalao;
import static view.Quartos.tblQuartos;
import static view.RealizarServiços.*;
import view2.*;

/**
 *
 * @author Ramiro Dantas
 */
public class DashboardGERENTE extends javax.swing.JFrame {
     Connection conexao = null;
        PreparedStatement pst = null;
    ResultSet rs = null;
        private void read(){
        String sql = "Select * from pedidoservico";        
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
           
                tblServico.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
        } catch (Exception e) {
            new Erro().setVisible(true);
        }    
    }
        
        private void add() {
        String sql = "Select * from quartos";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            tblQuartos.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
        } catch (Exception e) {
            new Erro().setVisible(true);
        }
    }
        
                private void inserir(){
             String sql = "Select * from alugarsalao";        
        try { 
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
                tblSalao.setModel(DbUtils.resultSetToTableModel(rs));
                pst.close();
        } catch (Exception e) {
            new Erro().setVisible(true);
        }
        }
    public DashboardGERENTE() {
        initComponents();
        conexao = ModulodeConexão.conector();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fechar1 = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Painelprincipal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Hóspede = new javax.swing.JButton();
        Reserva = new javax.swing.JButton();
        Serviços = new javax.swing.JButton();
        Relatórios = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        Recepcionista = new javax.swing.JButton();
        Salao = new javax.swing.JButton();
        Quartos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerente");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 0, 72));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fechar1.setFont(new java.awt.Font("SF Sports Night NS Upright", 1, 36)); // NOI18N
        fechar1.setForeground(new java.awt.Color(255, 255, 255));
        fechar1.setText("X");
        fechar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fechar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fechar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fechar1MouseExited(evt);
            }
        });
        jPanel1.add(fechar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        minimizar.setFont(new java.awt.Font("Rubik", 1, 36)); // NOI18N
        minimizar.setForeground(new java.awt.Color(255, 255, 255));
        minimizar.setText("_");
        minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizarMouseExited(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("User");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 730, 60));

        jDesktopPane1.setBackground(new java.awt.Color(1, 0, 56));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dash.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 730, 630));

        jPanel2.setBackground(new java.awt.Color(41, 58, 128));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Gerente.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 57, -1, -1));

        Painelprincipal.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Painelprincipal.setForeground(new java.awt.Color(255, 255, 255));
        Painelprincipal.setText("Gerente");
        Painelprincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Painelprincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PainelprincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PainelprincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PainelprincipalMouseExited(evt);
            }
        });
        jPanel2.add(Painelprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(243, 148, 34));
        jLabel3.setText("_____________");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        Hóspede.setBackground(new java.awt.Color(1, 0, 72));
        Hóspede.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Hóspede.setForeground(new java.awt.Color(255, 255, 255));
        Hóspede.setText("Hóspede");
        Hóspede.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Hóspede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hóspede.setFocusPainted(false);
        Hóspede.setPreferredSize(new java.awt.Dimension(89, 28));
        Hóspede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HóspedeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HóspedeMouseExited(evt);
            }
        });
        Hóspede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HóspedeActionPerformed(evt);
            }
        });
        jPanel2.add(Hóspede, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 240, 40));

        Reserva.setBackground(new java.awt.Color(1, 0, 72));
        Reserva.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Reserva.setForeground(new java.awt.Color(255, 255, 255));
        Reserva.setText("Reserva");
        Reserva.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Reserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reserva.setFocusPainted(false);
        Reserva.setPreferredSize(new java.awt.Dimension(89, 28));
        Reserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReservaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReservaMouseExited(evt);
            }
        });
        Reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservaActionPerformed(evt);
            }
        });
        jPanel2.add(Reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 240, 40));

        Serviços.setBackground(new java.awt.Color(1, 0, 72));
        Serviços.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Serviços.setForeground(new java.awt.Color(255, 255, 255));
        Serviços.setText("Serviços");
        Serviços.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Serviços.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Serviços.setFocusPainted(false);
        Serviços.setPreferredSize(new java.awt.Dimension(89, 28));
        Serviços.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ServiçosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ServiçosMouseExited(evt);
            }
        });
        Serviços.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiçosActionPerformed(evt);
            }
        });
        jPanel2.add(Serviços, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 240, 40));

        Relatórios.setBackground(new java.awt.Color(1, 0, 72));
        Relatórios.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Relatórios.setForeground(new java.awt.Color(255, 255, 255));
        Relatórios.setText("Relatórios");
        Relatórios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Relatórios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Relatórios.setFocusPainted(false);
        Relatórios.setPreferredSize(new java.awt.Dimension(89, 28));
        Relatórios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RelatóriosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RelatóriosMouseExited(evt);
            }
        });
        Relatórios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatóriosActionPerformed(evt);
            }
        });
        jPanel2.add(Relatórios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 240, 40));

        Sair.setBackground(new java.awt.Color(1, 0, 72));
        Sair.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Sair.setForeground(new java.awt.Color(255, 255, 255));
        Sair.setText("Sair");
        Sair.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sair.setFocusPainted(false);
        Sair.setPreferredSize(new java.awt.Dimension(89, 28));
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SairMouseExited(evt);
            }
        });
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        jPanel2.add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 240, 40));

        Recepcionista.setBackground(new java.awt.Color(1, 0, 72));
        Recepcionista.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Recepcionista.setForeground(new java.awt.Color(255, 255, 255));
        Recepcionista.setText("Recepcionista");
        Recepcionista.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Recepcionista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Recepcionista.setFocusPainted(false);
        Recepcionista.setPreferredSize(new java.awt.Dimension(89, 28));
        Recepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RecepcionistaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RecepcionistaMouseExited(evt);
            }
        });
        Recepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecepcionistaActionPerformed(evt);
            }
        });
        jPanel2.add(Recepcionista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 240, 40));

        Salao.setBackground(new java.awt.Color(1, 0, 72));
        Salao.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Salao.setForeground(new java.awt.Color(255, 255, 255));
        Salao.setText("Salão");
        Salao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Salao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salao.setFocusPainted(false);
        Salao.setPreferredSize(new java.awt.Dimension(89, 28));
        Salao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalaoMouseExited(evt);
            }
        });
        Salao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaoActionPerformed(evt);
            }
        });
        jPanel2.add(Salao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 240, 40));

        Quartos.setBackground(new java.awt.Color(1, 0, 72));
        Quartos.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Quartos.setForeground(new java.awt.Color(255, 255, 255));
        Quartos.setText("Quartos");
        Quartos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        Quartos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Quartos.setFocusPainted(false);
        Quartos.setPreferredSize(new java.awt.Dimension(89, 28));
        Quartos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QuartosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QuartosMouseExited(evt);
            }
        });
        Quartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuartosActionPerformed(evt);
            }
        });
        jPanel2.add(Quartos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 240, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 720, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
            DashboardGERENTE.this.dispose();
            
       new TelaDeLogin2().setVisible(true);
    }//GEN-LAST:event_SairActionPerformed

    private void QuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuartosActionPerformed
       Quartos Q = new Quartos();
       jDesktopPane1.add(Q);
       Q.setVisible(true);
       ((BasicInternalFrameUI)Q.getUI()).setNorthPane(null);
       add();
    }//GEN-LAST:event_QuartosActionPerformed

    private void RecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecepcionistaActionPerformed
        CadastrarRecepcionista Cr = new CadastrarRecepcionista();
        jDesktopPane1.add(Cr);
        Cr.setVisible(true);
        ((BasicInternalFrameUI)Cr.getUI()).setNorthPane(null);
    }//GEN-LAST:event_RecepcionistaActionPerformed

    private void HóspedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HóspedeActionPerformed
         CadastrarHóspede Ch = new CadastrarHóspede();
        jDesktopPane1.add(Ch);
        Ch.setVisible(true);
        ((BasicInternalFrameUI)Ch.getUI()).setNorthPane(null);
    }//GEN-LAST:event_HóspedeActionPerformed

    private void ReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservaActionPerformed
       RealizarReserva Rr = new RealizarReserva();
       jDesktopPane1.add(Rr);
       Rr.setVisible(true);
       ((BasicInternalFrameUI)Rr.getUI()).setNorthPane(null);        
    }//GEN-LAST:event_ReservaActionPerformed

    private void minimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseExited

        minimizar.setForeground(Color.WHITE);
    }//GEN-LAST:event_minimizarMouseExited

    private void minimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseEntered

        minimizar.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_minimizarMouseEntered

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked

        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void fechar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechar1MouseExited
        fechar1.setForeground(Color.WHITE);
    }//GEN-LAST:event_fechar1MouseExited

    private void fechar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechar1MouseEntered
        fechar1.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_fechar1MouseEntered

    private void fechar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechar1MouseClicked

        System.exit(0);
    }//GEN-LAST:event_fechar1MouseClicked

    private void SalaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalaoMouseEntered
        Salao.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_SalaoMouseEntered

    private void SalaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalaoMouseExited
        Salao.setForeground(Color.WHITE);
    }//GEN-LAST:event_SalaoMouseExited

    private void SalaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaoActionPerformed
       AlugarSalão As = new AlugarSalão();
       jDesktopPane1.add(As);
       As.setVisible(true);
       ((BasicInternalFrameUI)As.getUI()).setNorthPane(null);
       inserir();
    }//GEN-LAST:event_SalaoActionPerformed

    private void RecepcionistaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecepcionistaMouseEntered
       Recepcionista.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_RecepcionistaMouseEntered

    private void RecepcionistaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecepcionistaMouseExited
        Recepcionista.setForeground(Color.WHITE);
    }//GEN-LAST:event_RecepcionistaMouseExited

    private void HóspedeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HóspedeMouseEntered
      Hóspede.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_HóspedeMouseEntered

    private void HóspedeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HóspedeMouseExited
        Hóspede.setForeground(Color.WHITE);
    }//GEN-LAST:event_HóspedeMouseExited

    private void ReservaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservaMouseEntered
        Reserva.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_ReservaMouseEntered

    private void ReservaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservaMouseExited
        Reserva.setForeground(Color.WHITE);
    }//GEN-LAST:event_ReservaMouseExited

    private void ServiçosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServiçosMouseEntered
        Serviços.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_ServiçosMouseEntered

    private void ServiçosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServiçosMouseExited
        Serviços.setForeground(Color.WHITE);
    }//GEN-LAST:event_ServiçosMouseExited

    private void RelatóriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelatóriosMouseEntered
        Relatórios.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_RelatóriosMouseEntered

    private void RelatóriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelatóriosMouseExited
        Relatórios.setForeground(Color.WHITE);
    }//GEN-LAST:event_RelatóriosMouseExited

    private void QuartosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuartosMouseEntered
     Quartos.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_QuartosMouseEntered

    private void QuartosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuartosMouseExited
        Quartos.setForeground(Color.WHITE);
    }//GEN-LAST:event_QuartosMouseExited

    private void SairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseEntered
       Sair.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_SairMouseEntered

    private void SairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseExited
        Sair.setForeground(Color.WHITE);
    }//GEN-LAST:event_SairMouseExited

    private void PainelprincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PainelprincipalMouseEntered
        Painelprincipal.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_PainelprincipalMouseEntered

    private void PainelprincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PainelprincipalMouseExited
        Painelprincipal.setForeground(Color.WHITE);
    }//GEN-LAST:event_PainelprincipalMouseExited

    private void PainelprincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PainelprincipalMouseClicked
       PainelPrincipal Pp = new PainelPrincipal();
       jDesktopPane1.add(Pp);
       Pp.setVisible(true);
       ((BasicInternalFrameUI)Pp.getUI()).setNorthPane(null);   
    }//GEN-LAST:event_PainelprincipalMouseClicked

    private void RelatóriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatóriosActionPerformed
        GerarRelatórios Gr = new GerarRelatórios();
        jDesktopPane1.add(Gr);
        Gr.setVisible(true);
        ((BasicInternalFrameUI)Gr.getUI()).setNorthPane(null);   
    }//GEN-LAST:event_RelatóriosActionPerformed

    private void ServiçosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiçosActionPerformed
       RealizarServiços Rs = new RealizarServiços();
       jDesktopPane1.add(Rs);
       Rs.setVisible(true);
       ((BasicInternalFrameUI)Rs.getUI()).setNorthPane(null);  
       read();
    }//GEN-LAST:event_ServiçosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardGERENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardGERENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardGERENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardGERENTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardGERENTE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hóspede;
    private javax.swing.JLabel Painelprincipal;
    private javax.swing.JButton Quartos;
    private javax.swing.JButton Recepcionista;
    private javax.swing.JButton Relatórios;
    private javax.swing.JButton Reserva;
    private javax.swing.JButton Sair;
    private javax.swing.JButton Salao;
    private javax.swing.JButton Serviços;
    private javax.swing.JLabel fechar1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel minimizar;
    // End of variables declaration//GEN-END:variables
}
