/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import view2.EstadiaFechada;
import java.sql.*;
import dal.ModulodeConexão;
import static view.RealizarReserva.*;
import view2.Campos;
import view2.Erro;

public class FecharEstadia extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    private void remover2() {
        String sql = "delete from reservaquarto where idclien=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtResIDPes.getText());
            pst.executeUpdate();
            pst.close();
        } catch (Exception e) {
            new Erro().setVisible(true);

        }
    }

    private void remover3() {
        String sql = "delete from pedidos where idquarto=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, cbResPes.getSelectedItem().toString());
            pst.executeUpdate();
            pst.close();
        } catch (Exception e) {
            new Erro().setVisible(true);

        }
    }

    public FecharEstadia() {
        initComponents();
        conexao = ModulodeConexão.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEstNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEstFone = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        Excluir = new javax.swing.JButton();
        txtEstCPF = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEstEntrada = new javax.swing.JFormattedTextField();
        txtEstValoradd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEstSaida = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        FecharEstadia = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtEstEmail = new javax.swing.JTextField();
        txtEstValor = new javax.swing.JTextField();
        txtEstValorTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtEstNome.setBackground(new java.awt.Color(255, 255, 255));
        txtEstNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtEstNome.setForeground(new java.awt.Color(0, 0, 0));
        txtEstNome.setBorder(null);
        txtEstNome.setPreferredSize(new java.awt.Dimension(55, 25));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hóspede");

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Telefone");

        txtEstFone.setBackground(new java.awt.Color(255, 255, 255));
        txtEstFone.setBorder(null);
        try {
            txtEstFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtEstFone.setPreferredSize(new java.awt.Dimension(103, 25));
        txtEstFone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstFoneActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("CPF");

        Excluir.setBackground(new java.awt.Color(25, 14, 79));
        Excluir.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Excluir.setForeground(new java.awt.Color(255, 255, 255));
        Excluir.setText("Voltar");
        Excluir.setAlignmentY(0.0F);
        Excluir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 0, 56), 2, true));
        Excluir.setBorderPainted(false);
        Excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Excluir.setFocusPainted(false);
        Excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExcluirMouseExited(evt);
            }
        });
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        txtEstCPF.setBackground(new java.awt.Color(255, 255, 255));
        txtEstCPF.setBorder(null);
        try {
            txtEstCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtEstCPF.setPreferredSize(new java.awt.Dimension(103, 25));
        txtEstCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstCPFActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Data de entrada");

        txtEstEntrada.setBackground(new java.awt.Color(255, 255, 255));
        txtEstEntrada.setBorder(null);
        try {
            txtEstEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtEstEntrada.setPreferredSize(new java.awt.Dimension(103, 25));
        txtEstEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstEntradaActionPerformed(evt);
            }
        });

        txtEstValoradd.setBackground(new java.awt.Color(229, 229, 229));
        txtEstValoradd.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtEstValoradd.setForeground(new java.awt.Color(0, 0, 0));
        txtEstValoradd.setText("R$50,00");
        txtEstValoradd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtEstValoradd.setPreferredSize(new java.awt.Dimension(55, 25));
        txtEstValoradd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEstValoraddMouseClicked(evt);
            }
        });
        txtEstValoradd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstValoraddActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Data de saída");

        txtEstSaida.setBackground(new java.awt.Color(255, 255, 255));
        txtEstSaida.setBorder(null);
        try {
            txtEstSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtEstSaida.setPreferredSize(new java.awt.Dimension(103, 25));
        txtEstSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstSaidaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Valor da Estadia");

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Serviços Adicionais");

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Valor Total");

        FecharEstadia.setBackground(new java.awt.Color(25, 14, 79));
        FecharEstadia.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        FecharEstadia.setForeground(new java.awt.Color(255, 255, 255));
        FecharEstadia.setText("Fechar Conta");
        FecharEstadia.setAlignmentY(0.0F);
        FecharEstadia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 0, 56), 2, true));
        FecharEstadia.setBorderPainted(false);
        FecharEstadia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FecharEstadia.setFocusPainted(false);
        FecharEstadia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FecharEstadiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FecharEstadiaMouseExited(evt);
            }
        });
        FecharEstadia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharEstadiaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Email");

        txtEstEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEstEmail.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtEstEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEstEmail.setBorder(null);
        txtEstEmail.setPreferredSize(new java.awt.Dimension(55, 25));

        txtEstValor.setBackground(new java.awt.Color(229, 229, 229));
        txtEstValor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtEstValor.setForeground(new java.awt.Color(0, 0, 0));
        txtEstValor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtEstValor.setPreferredSize(new java.awt.Dimension(55, 25));
        txtEstValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEstValorMouseClicked(evt);
            }
        });
        txtEstValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstValorActionPerformed(evt);
            }
        });

        txtEstValorTotal.setBackground(new java.awt.Color(229, 229, 229));
        txtEstValorTotal.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtEstValorTotal.setForeground(new java.awt.Color(0, 0, 0));
        txtEstValorTotal.setText("R$550,00");
        txtEstValorTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtEstValorTotal.setPreferredSize(new java.awt.Dimension(55, 25));
        txtEstValorTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEstValorTotalMouseClicked(evt);
            }
        });
        txtEstValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstValorTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEstValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEstEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)
                                .addComponent(txtEstNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEstCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel10)
                            .addComponent(Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstValor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtEstEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(FecharEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(txtEstFone, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9)
                                        .addComponent(txtEstSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)
                                        .addComponent(txtEstValoradd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstValoradd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEstValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FecharEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEstFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstFoneActionPerformed

    }//GEN-LAST:event_txtEstFoneActionPerformed

    private void ExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExcluirMouseEntered
        Excluir.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_ExcluirMouseEntered

    private void ExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExcluirMouseExited
        Excluir.setForeground(Color.WHITE);
    }//GEN-LAST:event_ExcluirMouseExited

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        FecharEstadia.this.dispose();
    }//GEN-LAST:event_ExcluirActionPerformed

    private void txtEstCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstCPFActionPerformed

    }//GEN-LAST:event_txtEstCPFActionPerformed

    private void txtEstEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstEntradaActionPerformed

    private void txtEstSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstSaidaActionPerformed

    private void FecharEstadiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharEstadiaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_FecharEstadiaMouseEntered

    private void FecharEstadiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharEstadiaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_FecharEstadiaMouseExited

    private void FecharEstadiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharEstadiaActionPerformed
        if (txtEstValorTotal.getText().equals("")) {
            new Campos().setVisible(true);
        } else {
            remover2();
            remover3();
            new EstadiaFechada().setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_FecharEstadiaActionPerformed


    private void txtEstValoraddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEstValoraddMouseClicked

    }//GEN-LAST:event_txtEstValoraddMouseClicked

    private void txtEstValoraddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstValoraddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstValoraddActionPerformed

    private void txtEstValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEstValorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstValorMouseClicked

    private void txtEstValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstValorActionPerformed

    private void txtEstValorTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEstValorTotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstValorTotalMouseClicked

    private void txtEstValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstValorTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FecharEstadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FecharEstadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FecharEstadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FecharEstadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FecharEstadia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Excluir;
    private javax.swing.JButton FecharEstadia;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JFormattedTextField txtEstCPF;
    public static javax.swing.JTextField txtEstEmail;
    public static javax.swing.JFormattedTextField txtEstEntrada;
    public static javax.swing.JFormattedTextField txtEstFone;
    public static javax.swing.JTextField txtEstNome;
    public static javax.swing.JFormattedTextField txtEstSaida;
    public static javax.swing.JTextField txtEstValor;
    public static javax.swing.JTextField txtEstValorTotal;
    public static javax.swing.JTextField txtEstValoradd;
    // End of variables declaration//GEN-END:variables
}
