/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import Relatórios.*;
import java.sql.*;
import dal.ModulodeConexão;
import view2.*;
/**
 *
 * @author Ramiro Dantas
 */
public class GerarRelatórios extends javax.swing.JInternalFrame {   
    Connection conexao = null;
    /**
     * Creates new form FecharEstadia
     */
    public GerarRelatórios() {
        initComponents();
        conexao = ModulodeConexão.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RelGer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        RelRec = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        RelHos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        RelRes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RelSer = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        RelSal = new javax.swing.JButton();
        RelQua = new javax.swing.JButton();

        setBorder(null);

        jPanel2.setBackground(new java.awt.Color(1, 0, 56));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerar Relatórios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(228, 228, 228))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Gerentes");

        RelGer.setBackground(new java.awt.Color(255, 255, 255));
        RelGer.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        RelGer.setForeground(new java.awt.Color(255, 255, 255));
        RelGer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf.png"))); // NOI18N
        RelGer.setAlignmentY(0.0F);
        RelGer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 0, 56), 2, true));
        RelGer.setBorderPainted(false);
        RelGer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RelGer.setFocusPainted(false);
        RelGer.setPreferredSize(new java.awt.Dimension(32, 22));
        RelGer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RelGerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RelGerMouseExited(evt);
            }
        });
        RelGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelGerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Recepcionistas");

        RelRec.setBackground(new java.awt.Color(255, 255, 255));
        RelRec.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        RelRec.setForeground(new java.awt.Color(255, 255, 255));
        RelRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf.png"))); // NOI18N
        RelRec.setAlignmentY(0.0F);
        RelRec.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 0, 56), 2, true));
        RelRec.setBorderPainted(false);
        RelRec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RelRec.setFocusPainted(false);
        RelRec.setPreferredSize(new java.awt.Dimension(32, 22));
        RelRec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RelRecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RelRecMouseExited(evt);
            }
        });
        RelRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelRecActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Reservas");

        RelHos.setBackground(new java.awt.Color(255, 255, 255));
        RelHos.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        RelHos.setForeground(new java.awt.Color(255, 255, 255));
        RelHos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf.png"))); // NOI18N
        RelHos.setAlignmentY(0.0F);
        RelHos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 0, 56), 2, true));
        RelHos.setBorderPainted(false);
        RelHos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RelHos.setFocusPainted(false);
        RelHos.setPreferredSize(new java.awt.Dimension(32, 22));
        RelHos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RelHosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RelHosMouseExited(evt);
            }
        });
        RelHos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelHosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hóspedes");

        RelRes.setBackground(new java.awt.Color(255, 255, 255));
        RelRes.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        RelRes.setForeground(new java.awt.Color(255, 255, 255));
        RelRes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf.png"))); // NOI18N
        RelRes.setAlignmentY(0.0F);
        RelRes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 0, 56), 2, true));
        RelRes.setBorderPainted(false);
        RelRes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RelRes.setFocusPainted(false);
        RelRes.setPreferredSize(new java.awt.Dimension(32, 22));
        RelRes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RelResMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RelResMouseExited(evt);
            }
        });
        RelRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelResActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Serviços");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Salão");

        RelSer.setBackground(new java.awt.Color(255, 255, 255));
        RelSer.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        RelSer.setForeground(new java.awt.Color(255, 255, 255));
        RelSer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf.png"))); // NOI18N
        RelSer.setAlignmentY(0.0F);
        RelSer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 0, 56), 2, true));
        RelSer.setBorderPainted(false);
        RelSer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RelSer.setFocusPainted(false);
        RelSer.setPreferredSize(new java.awt.Dimension(32, 22));
        RelSer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RelSerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RelSerMouseExited(evt);
            }
        });
        RelSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelSerActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Quartos");

        RelSal.setBackground(new java.awt.Color(255, 255, 255));
        RelSal.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        RelSal.setForeground(new java.awt.Color(255, 255, 255));
        RelSal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf.png"))); // NOI18N
        RelSal.setAlignmentY(0.0F);
        RelSal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 0, 56), 2, true));
        RelSal.setBorderPainted(false);
        RelSal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RelSal.setFocusPainted(false);
        RelSal.setPreferredSize(new java.awt.Dimension(32, 22));
        RelSal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RelSalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RelSalMouseExited(evt);
            }
        });
        RelSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelSalActionPerformed(evt);
            }
        });

        RelQua.setBackground(new java.awt.Color(255, 255, 255));
        RelQua.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        RelQua.setForeground(new java.awt.Color(255, 255, 255));
        RelQua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf.png"))); // NOI18N
        RelQua.setAlignmentY(0.0F);
        RelQua.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 0, 56), 2, true));
        RelQua.setBorderPainted(false);
        RelQua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RelQua.setFocusPainted(false);
        RelQua.setPreferredSize(new java.awt.Dimension(32, 22));
        RelQua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RelQuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RelQuaMouseExited(evt);
            }
        });
        RelQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelQuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RelGer, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4))
                            .addComponent(RelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RelSer, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RelRec, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RelQua, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel6)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RelSal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RelHos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(120, 120, 120))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RelGer, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RelRec, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(RelHos, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RelSal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RelSer, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RelQua, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved

    }//GEN-LAST:event_jPanel2MouseMoved

    private void RelGerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelGerMouseEntered
       
    }//GEN-LAST:event_RelGerMouseEntered

    private void RelGerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelGerMouseExited
        
    }//GEN-LAST:event_RelGerMouseExited

    private void RelGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelGerActionPerformed

    }//GEN-LAST:event_RelGerActionPerformed

    private void RelRecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelRecMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RelRecMouseEntered

    private void RelRecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelRecMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RelRecMouseExited

    private void RelRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelRecActionPerformed
        new ImprimirRel2().setVisible(true);
    }//GEN-LAST:event_RelRecActionPerformed

    private void RelHosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelHosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RelHosMouseEntered

    private void RelHosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelHosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RelHosMouseExited

    private void RelHosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelHosActionPerformed
        new ImprimirRel().setVisible(true);
    }//GEN-LAST:event_RelHosActionPerformed

    private void RelResMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelResMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RelResMouseEntered

    private void RelResMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelResMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RelResMouseExited

    private void RelResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelResActionPerformed

    }//GEN-LAST:event_RelResActionPerformed

    private void RelSerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelSerMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RelSerMouseEntered

    private void RelSerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelSerMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RelSerMouseExited

    private void RelSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelSerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelSerActionPerformed

    private void RelSalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelSalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RelSalMouseEntered

    private void RelSalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelSalMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RelSalMouseExited

    private void RelSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelSalActionPerformed

    private void RelQuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelQuaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RelQuaMouseEntered

    private void RelQuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelQuaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RelQuaMouseExited

    private void RelQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelQuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelQuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RelGer;
    private javax.swing.JButton RelHos;
    private javax.swing.JButton RelQua;
    private javax.swing.JButton RelRec;
    private javax.swing.JButton RelRes;
    private javax.swing.JButton RelSal;
    private javax.swing.JButton RelSer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
