/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.Color;
/**
 *
 * @author Ramiro Dantas
 */
public class PainelPrincipalADM extends javax.swing.JInternalFrame {

    /**
     * Creates new form PainelPrincipalADM
     */
    public PainelPrincipalADM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastrarAdm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);

        CadastrarAdm.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        CadastrarAdm.setForeground(new java.awt.Color(255, 255, 255));
        CadastrarAdm.setText("*Cadastrar Administrador");
        CadastrarAdm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CadastrarAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarAdmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CadastrarAdmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CadastrarAdmMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dash.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(CadastrarAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(CadastrarAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarAdmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarAdmMouseClicked
        new CadastrarADM().setVisible(true);
    }//GEN-LAST:event_CadastrarAdmMouseClicked

    private void CadastrarAdmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarAdmMouseEntered
        CadastrarAdm.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_CadastrarAdmMouseEntered

    private void CadastrarAdmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarAdmMouseExited
        CadastrarAdm.setForeground(Color.WHITE);
    }//GEN-LAST:event_CadastrarAdmMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadastrarAdm;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
