/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Font;
import javax.swing.table.JTableHeader;
import java.sql.*;
import dal.ModulodeConexão;
import net.proteanit.sql.DbUtils;
import view2.*;

/**
 *
 * @author Ramiro Dantas
 */
public class Quartos extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    private void alterar() {
        String sql = "update quartos set idquarto = ?, disponibilidade = ? where idquarto = ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, cbQuar.getSelectedItem().toString());
            pst.setString(2, cbQuarDis.getSelectedItem().toString());
            pst.setString(3, cbQuar.getSelectedItem().toString());
            if (cbQuar.getSelectedItem().toString().equals("Selecione o quarto...") || cbQuarDis.getSelectedItem().toString().equals("Disponibilidade")) {
                new Campos().setVisible(true);
                pst.close();
            } else {
                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    new QuartoATT().setVisible(true);
                    cbQuarDis.setSelectedItem("Disponibilidade");
                    pst.close();
                }
            }

        } catch (Exception e) {
            new Erro().setVisible(true);

        }

    }

    private void consultar() {
        String sql = "Select * from quartos";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();

            tblQuartos.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
        } catch (Exception e) {
            new Erro().setVisible(true);
            System.out.println(e);
        }
    }

    /**
     * Creates new form Quartos
     */
    public Quartos() {
        initComponents();
        conexao = ModulodeConexão.conector();
        JTableHeader header = tblQuartos.getTableHeader();
        header.setBackground(new Color(83, 126, 197));
        header.setForeground(Color.BLACK);
        this.setFont(new Font("Sogoe Print 11 Simples", Font.BOLD, 12));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQuartos = new javax.swing.JTable();
        cbQuarDis = new javax.swing.JComboBox<>();
        cbQuar = new javax.swing.JComboBox<>();
        AlterarDados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);

        jPanel2.setBackground(new java.awt.Color(1, 0, 56));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quartos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(301, 301, 301))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quarto", "Disponibilidade"
            }
        ));
        jScrollPane2.setViewportView(tblQuartos);

        cbQuarDis.setBackground(new java.awt.Color(255, 255, 255));
        cbQuarDis.setEditable(true);
        cbQuarDis.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        cbQuarDis.setForeground(new java.awt.Color(0, 0, 0));
        cbQuarDis.setMaximumRowCount(9);
        cbQuarDis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponibilidade", "Sim ", "Não", "Ocupado" }));
        cbQuarDis.setToolTipText("");
        cbQuarDis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbQuarDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQuarDisActionPerformed(evt);
            }
        });

        cbQuar.setBackground(new java.awt.Color(255, 255, 255));
        cbQuar.setEditable(true);
        cbQuar.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        cbQuar.setForeground(new java.awt.Color(0, 0, 0));
        cbQuar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o quarto...", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "201", "202", "203", "204", "205", "206", "207", "208", "209", "210", "301", "302", "303", "304", "305", "306", "307", "308", "309", "310" }));
        cbQuar.setToolTipText("");
        cbQuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbQuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQuarActionPerformed(evt);
            }
        });

        AlterarDados.setBackground(new java.awt.Color(255, 255, 255));
        AlterarDados.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        AlterarDados.setForeground(new java.awt.Color(255, 255, 255));
        AlterarDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        AlterarDados.setAlignmentY(0.0F);
        AlterarDados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 0, 56), 2, true));
        AlterarDados.setBorderPainted(false);
        AlterarDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AlterarDados.setFocusPainted(false);
        AlterarDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AlterarDadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AlterarDadosMouseExited(evt);
            }
        });
        AlterarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarDadosActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Hotel_1.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbQuarDis, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(AlterarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbQuar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(cbQuar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(cbQuarDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(AlterarDados)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved

    }//GEN-LAST:event_jPanel2MouseMoved

    private void AlterarDadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlterarDadosMouseEntered
        AlterarDados.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_AlterarDadosMouseEntered

    private void AlterarDadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlterarDadosMouseExited
        AlterarDados.setForeground(Color.WHITE);
    }//GEN-LAST:event_AlterarDadosMouseExited

    private void AlterarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarDadosActionPerformed
        alterar();
        consultar();
    }//GEN-LAST:event_AlterarDadosActionPerformed

    private void cbQuarDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQuarDisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQuarDisActionPerformed

    private void cbQuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterarDados;
    private javax.swing.JComboBox<String> cbQuar;
    private javax.swing.JComboBox<String> cbQuarDis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tblQuartos;
    // End of variables declaration//GEN-END:variables
}
