/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Font;
import javax.swing.table.JTableHeader;
import java.sql.*;
import dal.ModulodeConexão;
import net.proteanit.sql.DbUtils;
import view2.*;
/**
 *
 * @author Ramiro Dantas
 */
public class RealizarServiços extends javax.swing.JInternalFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    private void consultar_servico(){
        String sql = "Select * from pedidoservico where idquarto like ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,cbSerPes.getSelectedItem().toString() + "%");
            rs = pst.executeQuery();
            
            tblServico.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
        } catch (Exception e) {
            new Erro().setVisible(true);
        }
    }
    
    private void Consultar(){
        String sql ="Select * from pedidoservico where idquarto=?";
        try {
               pst = conexao.prepareStatement(sql);
               pst.setString(1,cbSerPes.getSelectedItem().toString());
               rs = pst.executeQuery();
               if(rs.next()){
                   txtSerQuarto.setSelectedItem(rs.getString(2));
                   txtSerIDH.setText(rs.getString(3));
                   txtSerServico.setText(rs.getString(5));
                   txtSerValor.setText(rs.getString(6));
                   pst.close();
               } else {
                    new ServNEncontrado().setVisible(true);
                    txtSerIDH.setText("");
                    txtSerQuarto.setSelectedItem("Quartos");
                    txtSerValor.setText("");
                    txtSerServico.setText("");
                    cbSerPes.setSelectedItem("Selecione o quarto...");
                    pst.close();
               }
           } catch (Exception e) {
               new Erro().setVisible(true);
           }
    }
    
    private void alterar(){
        String sql = "update pedidoservico set idquarto=?,idclien=?,servico =?,valorservico =? where idquarto=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,txtSerQuarto.getSelectedItem().toString());
            pst.setString(2, txtSerIDH.getText());
            pst.setString(3, txtSerServico.getText());
            pst.setString(4, txtSerValor.getText());
            pst.setString(5, cbSerPes.getSelectedItem().toString());
            if (txtSerQuarto.getSelectedItem().equals("Quartos") || txtSerIDH.getText().isEmpty() || txtSerServico.getText().isEmpty() || txtSerValor.getText().isEmpty()) {
                new Campos().setVisible(true);
                pst.close();
            } else {

                //a linha abaixo atualiza a tabela usuários
                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    new ServicoATT().setVisible(true);
                    txtSerIDH.setText("");
                    txtSerQuarto.setSelectedItem("Quartos");
                    txtSerValor.setText("");
                    txtSerServico.setText("");
                    pst.close();
                }
            }
        } catch (Exception e) {
            new Erro().setVisible(true);
        }
            }
    
    private void remover(){
        if(txtSerIDH.getText().isEmpty()){
        new ServicoNEncontrado().setVisible(true);
        } else {
            new ApagarServico().setVisible(true);
        }
    }
    
    public RealizarServiços() {
        initComponents();
        conexao = ModulodeConexão.conector();
        JTableHeader header = tblServico.getTableHeader();
        header.setBackground(new Color(83,126,197));
        header.setForeground(Color.BLACK);
        this.setFont(new Font ("Sogoe Print 11 Simples", Font.BOLD,12));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServico = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        txtSerIDH = new javax.swing.JTextField();
        cbSerPes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        CancelarServiço = new javax.swing.JButton();
        AlterarServiço = new javax.swing.JButton();
        txtSerServico = new javax.swing.JTextField();
        txtSerValor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSerQuarto = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(1, 0, 56));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Serviços");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tblServico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tblServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id servico", "Idquarto", "idclien", "Dataservico", "servico", "Valorservico"
            }
        ));
        jScrollPane1.setViewportView(tblServico);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ID do Hóspede");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Serviço");

        Buscar.setBackground(new java.awt.Color(25, 14, 79));
        Buscar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Buscar.setForeground(new java.awt.Color(255, 255, 255));
        Buscar.setText("Buscar");
        Buscar.setAlignmentY(0.0F);
        Buscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 0, 56), 2, true));
        Buscar.setBorderPainted(false);
        Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buscar.setFocusPainted(false);
        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BuscarMouseExited(evt);
            }
        });
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        txtSerIDH.setBackground(new java.awt.Color(229, 229, 229));
        txtSerIDH.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtSerIDH.setForeground(new java.awt.Color(0, 0, 0));
        txtSerIDH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSerIDH.setPreferredSize(new java.awt.Dimension(55, 25));
        txtSerIDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerIDHActionPerformed(evt);
            }
        });

        cbSerPes.setBackground(new java.awt.Color(255, 255, 255));
        cbSerPes.setEditable(true);
        cbSerPes.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        cbSerPes.setForeground(new java.awt.Color(0, 0, 0));
        cbSerPes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o quarto...", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "201", "202", "203", "204", "205", "206", "207", "208", "209", "210", "301", "302", "303", "304", "305", "306", "307", "308", "309", "310" }));
        cbSerPes.setToolTipText("");
        cbSerPes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbSerPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSerPesActionPerformed(evt);
            }
        });
        cbSerPes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbSerPesKeyReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar-service.png"))); // NOI18N

        CancelarServiço.setBackground(new java.awt.Color(255, 255, 255));
        CancelarServiço.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        CancelarServiço.setForeground(new java.awt.Color(255, 255, 255));
        CancelarServiço.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        CancelarServiço.setAlignmentY(0.0F);
        CancelarServiço.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 0, 56), 2, true));
        CancelarServiço.setBorderPainted(false);
        CancelarServiço.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelarServiço.setFocusPainted(false);
        CancelarServiço.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelarServiçoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelarServiçoMouseExited(evt);
            }
        });
        CancelarServiço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarServiçoActionPerformed(evt);
            }
        });

        AlterarServiço.setBackground(new java.awt.Color(255, 255, 255));
        AlterarServiço.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        AlterarServiço.setForeground(new java.awt.Color(255, 255, 255));
        AlterarServiço.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        AlterarServiço.setAlignmentY(0.0F);
        AlterarServiço.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 0, 56), 2, true));
        AlterarServiço.setBorderPainted(false);
        AlterarServiço.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AlterarServiço.setFocusPainted(false);
        AlterarServiço.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AlterarServiçoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AlterarServiçoMouseExited(evt);
            }
        });
        AlterarServiço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarServiçoActionPerformed(evt);
            }
        });

        txtSerServico.setBackground(new java.awt.Color(229, 229, 229));
        txtSerServico.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtSerServico.setForeground(new java.awt.Color(0, 0, 0));
        txtSerServico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSerServico.setPreferredSize(new java.awt.Dimension(55, 25));
        txtSerServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerServicoActionPerformed(evt);
            }
        });

        txtSerValor.setBackground(new java.awt.Color(229, 229, 229));
        txtSerValor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtSerValor.setForeground(new java.awt.Color(0, 0, 0));
        txtSerValor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSerValor.setPreferredSize(new java.awt.Dimension(55, 25));
        txtSerValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSerValorMouseClicked(evt);
            }
        });
        txtSerValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerValorActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Valor");

        txtSerQuarto.setBackground(new java.awt.Color(255, 255, 255));
        txtSerQuarto.setEditable(true);
        txtSerQuarto.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        txtSerQuarto.setForeground(new java.awt.Color(0, 0, 0));
        txtSerQuarto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quartos", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "201", "202", "203", "204", "205", "206", "207", "208", "209", "210", "301", "302", "303", "304", "305", "306", "307", "308", "309", "310" }));
        txtSerQuarto.setToolTipText("");
        txtSerQuarto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSerQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerQuartoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(txtSerIDH, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtSerQuarto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtSerValor, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                                .addComponent(txtSerServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbSerPes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Buscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(CancelarServiço, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AlterarServiço, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addGap(21, 21, 21))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerIDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSerServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSerPes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSerValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSerQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AlterarServiço, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CancelarServiço, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved

    }//GEN-LAST:event_jPanel1MouseMoved

    private void cbSerPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSerPesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSerPesActionPerformed

    private void BuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMouseEntered
        Buscar.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_BuscarMouseEntered

    private void BuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMouseExited
        Buscar.setForeground(Color.WHITE);
    }//GEN-LAST:event_BuscarMouseExited

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        consultar_servico();
        Consultar();
    }//GEN-LAST:event_BuscarActionPerformed

    private void CancelarServiçoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarServiçoMouseEntered
       CancelarServiço.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_CancelarServiçoMouseEntered

    private void CancelarServiçoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarServiçoMouseExited
      CancelarServiço.setForeground(Color.WHITE);
    }//GEN-LAST:event_CancelarServiçoMouseExited

    private void CancelarServiçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarServiçoActionPerformed
        remover();
    }//GEN-LAST:event_CancelarServiçoActionPerformed

    private void AlterarServiçoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlterarServiçoMouseEntered
       AlterarServiço.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_AlterarServiçoMouseEntered

    private void AlterarServiçoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlterarServiçoMouseExited
       AlterarServiço.setForeground(Color.WHITE);
    }//GEN-LAST:event_AlterarServiçoMouseExited

    private void AlterarServiçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarServiçoActionPerformed
        alterar();
        consultar_servico();
    }//GEN-LAST:event_AlterarServiçoActionPerformed

    private void txtSerServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerServicoActionPerformed

    private void txtSerIDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerIDHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerIDHActionPerformed

    private void txtSerValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerValorActionPerformed

    private void txtSerValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSerValorMouseClicked
        txtSerValor.setText("R$");
    }//GEN-LAST:event_txtSerValorMouseClicked

    private void cbSerPesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbSerPesKeyReleased
        
    }//GEN-LAST:event_cbSerPesKeyReleased

    private void txtSerQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerQuartoActionPerformed

    }//GEN-LAST:event_txtSerQuartoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterarServiço;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton CancelarServiço;
    public static javax.swing.JComboBox<String> cbSerPes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblServico;
    public static javax.swing.JTextField txtSerIDH;
    public static javax.swing.JComboBox<String> txtSerQuarto;
    public static javax.swing.JTextField txtSerServico;
    public static javax.swing.JTextField txtSerValor;
    // End of variables declaration//GEN-END:variables
}
