/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view2.UsuárioErrado;
import java.awt.Color;
import java.sql.*;
import dal.ModulodeConexão;
/**
 *
 * @author Ramiro Dantas
 */
public class TelaDeLogin2 extends javax.swing.JFrame {
       Connection conexao = null;
       PreparedStatement pst = null;
       ResultSet rs = null;
       
        public void logar(){
        String sql = "select * from users2 where login2=? and senha2=?";
           try {
              //as linhas abaixo preparam a consulta ao banco de dados em função do
              //que foi digitado nos campos de texto. O ? é substituido pelo conteúdo das variáveis.
              pst = conexao.prepareStatement(sql);
              pst.setString(1,txtusuario.getText());
              pst.setString(2,txtsenha.getText());
              //a linha abaixo executa a quer
              rs = pst.executeQuery();
              //se existir um usuario e senha correspondente
              if (rs.next()){
                 DashboardGERENTE Dg = new DashboardGERENTE();
                 Dg.setVisible(true);
                 TelaDeLogin2.this.dispose();
                 DashboardGERENTE.lblUsuario.setText(rs.getString(2));
                 conexao.close();
              }else {
                  new UsuárioErrado().setVisible(true);
                          
              }
           } catch (Exception e) {
              
                      
           }
           
}
       
       
       
       
    /**
     * Creates new form TeladDeLogin2
     */
    public TelaDeLogin2() {
        initComponents();
        conexao = ModulodeConexão.conector();
        
        if (conexao != null){
            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Right.png")));
        } else {
           lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/error.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtusuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtsenha = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        Gerente = new javax.swing.JLabel();
        Recep = new javax.swing.JLabel();
        Admin = new javax.swing.JLabel();
        Gerente2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Login-Gerente");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(243, 148, 34));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(1, 0, 72));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 0, 56), 4, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Hotel Blue Beach, vá em frente.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SF Sports Night NS", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 181, 209));
        jLabel2.setText("Boas Vindas!");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 240, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/check.png"))); // NOI18N
        jLabel4.setText(" Preços acessíveis.");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/check.png"))); // NOI18N
        jLabel5.setText(" Ágil no atendimento.");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/check.png"))); // NOI18N
        jLabel6.setText("  Qualidade nos serviços.");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 255));
        jLabel14.setText(" é que constitui um refugio da vida do lar. \"");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("\" A grande vantagem de um hotel");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 260, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coconut-tree.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 330, 390));

        btnLogin.setBackground(new java.awt.Color(25, 14, 79));
        btnLogin.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 52, 98), 1, true));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setFocusPainted(false);
        btnLogin.setPreferredSize(new java.awt.Dimension(89, 28));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 140, 50));

        txtusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtusuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(0, 0, 0));
        txtusuario.setBorder(null);
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 210, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Não aguento mais_1.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 120));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cadeado.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avatar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 30, -1));

        txtsenha.setBackground(new java.awt.Color(255, 255, 255));
        txtsenha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtsenha.setBorder(null);
        txtsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsenhaKeyPressed(evt);
            }
        });
        jPanel1.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 210, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sem título.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 250, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sem título.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 250, 40));

        lblStatus.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/error.png"))); // NOI18N
        jPanel1.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        Gerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manager.png"))); // NOI18N
        Gerente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Gerente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GerenteMouseClicked(evt);
            }
        });
        jPanel1.add(Gerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Recep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recept.png"))); // NOI18N
        Recep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Recep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecepMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RecepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RecepMouseExited(evt);
            }
        });
        jPanel1.add(Recep, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boss.png"))); // NOI18N
        Admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminMouseExited(evt);
            }
        });
        jPanel1.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        Gerente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manager.png"))); // NOI18N
        Gerente2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Gerente2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Gerente2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Gerente2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Gerente2MouseExited(evt);
            }
        });
        jPanel1.add(Gerente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        Desktop.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        btnLogin.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        btnLogin.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       logar();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsenhaKeyPressed

    }//GEN-LAST:event_txtsenhaKeyPressed

    private void GerenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GerenteMouseClicked

    }//GEN-LAST:event_GerenteMouseClicked

    private void RecepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecepMouseClicked
        this.dispose();
        new TelaDeLogin3().setVisible(true);
    }//GEN-LAST:event_RecepMouseClicked

    private void AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseClicked
      this.dispose();
      new Teladelogin().setVisible(true);
    }//GEN-LAST:event_AdminMouseClicked

    private void Gerente2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Gerente2MouseClicked
      
    }//GEN-LAST:event_Gerente2MouseClicked

    private void AdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseEntered
       Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png")));
    }//GEN-LAST:event_AdminMouseEntered

    private void AdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseExited
           Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boss.png")));  
    }//GEN-LAST:event_AdminMouseExited

    private void Gerente2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Gerente2MouseEntered
           Gerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png")));
    }//GEN-LAST:event_Gerente2MouseEntered

    private void Gerente2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Gerente2MouseExited
        Gerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manager.png")));
    }//GEN-LAST:event_Gerente2MouseExited

    private void RecepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecepMouseEntered
        Recep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.png")));
    }//GEN-LAST:event_RecepMouseEntered

    private void RecepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecepMouseExited
         Recep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recept.png")));
    }//GEN-LAST:event_RecepMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeLogin2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JLabel Gerente;
    private javax.swing.JLabel Gerente2;
    private javax.swing.JLabel Recep;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
